services:
  api:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=GameApiDb;User=root;Password=senha123;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy # <--- A MÁGICA: Só inicia a API se o banco estiver "Saudável"
    
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: GameApiDb
    ports:
      - "3306:3306"
    # Este bloco ensina o Docker a testar se o banco está vivo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10